### PR TITLE
Update russian translation

### PR DESCRIPTION
**Pull request by suiqa**

### CODE REVIEW

**Comment by NurKeinNeid** [comment]
Whats wrong with the translations from Lineage? You even change few things back to english here.

**Comment by suiqa** [comment]
Added missing strings and correction of the current translation

**Comment by suiqa** [comment]
Screenshot_20221120-161114

**Comment by NurKeinNeid** [comment]
Hmm ok, I will try to pick only the relevant parts from your commit

**Comment by NurKeinNeid** [comment]
I will also add back your previous translations btw

https://github.com/DerpFest-AOSP/frameworks_base/commit/71443f64a95d7db812de8067c543d4012a42aecb#diff-c809f13a5d38b36472843e01303db0c8f71d696bf914df3575f24c5e588559f7

**Comment by suiqa** [comment]
Okay

**Comment by NurKeinNeid** [comment]
Ok done and merged, see: https://github.com/DerpFest-AOSP/packages_apps_Updater/commit/64599a9885735761d849721b9efb066f65aa954f

**Pull request closed without merging**
